### ISSUE TITLE
Topographic phase removal

### ISSUE THREAD

**Issue by KamogeloBaloyi** [mundialis/esa-snap#20]
I've been trying to create an interferogram for my research but I keep getting an OperatorException error at the topographic phase removal stage. The error says "A problem has occurred during target product initialisation", without a message. What could the problem be?

**Comment by mmacata** [comment]
Out of the box I have no idea. How can the error be reproduced?

**Comment by KamogeloBaloyi** [comment]
I downloaded a dataset (SLC) from the Alaska Satellite Facility (ASF) , dated between February and the end of August of 2017. I then went through the steps given on the ASF website, under "How to create an interferogram". The error occurs everytime I reach the topographic phase removal stage.

Yesterday, I downloaded data from 2022 and I was able to get past the topographic phase removal stage.

**Comment by mmacata** [comment]
Sorry, I don't see how this is related to the Dockerfile provided here. The ASF provides a tutorial with graphical user interface of ESA’s Sentinel-1 Toolbox while this Dockerfile enables programmatic usage.
Maybe ask directly in ESA`s forum? https://forum.step.esa.int/
